"""create_shops_table_for_whatsapp_identity

Revision ID: 113f6c5b291d
Revises: 43950d56bcd0
Create Date: 2026-06-03 17:11:20.691624

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "113f6c5b291d"
down_revision: Union[str, None] = "43950d56bcd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
