"""add index to correlation_id

Revision ID: 43950d56bcd0
Revises: 6570fc21d8d4
Create Date: 2026-06-02 20:02:22.394503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43950d56bcd0"
down_revision: Union[str, None] = "6570fc21d8d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_conversation_events_correlation_id"),
        "conversation_events",
        ["correlation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_conversation_events_correlation_id"), table_name="conversation_events"
    )
    # ### end Alembic commands ###
