"""create users table

Revision ID: 4f67a335c2fb
Revises:
Create Date: 2026-06-01 20:32:00.843646

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4f67a335c2fb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
