"""SokoFlow-owned contracts for LLM Client interactions.

Defines provider-agnostic input and output data models for LLM communication.
"""

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class LLMMessage(BaseModel):
    """Represents a single message in the LLM conversation context."""

    model_config = ConfigDict(extra="forbid")

    role: str = Field(..., description="Message role (e.g. 'system', 'user', 'assistant').")
    content: str | None = Field(default=None, description="Message text content.")


class NormalizedToolCall(BaseModel):
    """Normalized tool call returned from an LLM provider."""

    model_config = ConfigDict(extra="forbid")

    id: str | None = Field(default=None, description="Optional provider tool call identifier.")
    name: str = Field(..., description="The requested tool name.")
    arguments: dict[str, Any] = Field(
        default_factory=dict, description="Parsed tool call arguments object."
    )


class LLMResponse(BaseModel):
    """Normalized output contract from LLMClient to SokoFlow application."""

    model_config = ConfigDict(extra="forbid")

    text: str | None = Field(
        default=None, description="Optional text content generated by the model."
    )
    tool_calls: list[NormalizedToolCall] = Field(
        default_factory=list, description="List of normalized tool calls requested by the model."
    )
    prompt_tokens: int = Field(default=0, description="Number of prompt tokens consumed.")
    completion_tokens: int = Field(default=0, description="Number of completion tokens consumed.")
    cost_usd: float = Field(default=0.0, description="Calculated or reported query cost in USD.")
    raw_response: dict[str, Any] | None = Field(
        default=None, description="Optional raw provider response payload for debugging/logging."
    )

    @property
    def has_tool_calls(self) -> bool:
        """Returns True if the response contains one or more tool calls."""
        return len(self.tool_calls) > 0

    @property
    def primary_tool_call(self) -> NormalizedToolCall | None:
        """Returns the first tool call if available, otherwise None."""
        return self.tool_calls[0] if self.tool_calls else None
